# Generated by Django 4.2.2 on 2023-06-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_remove_post_cat_delete_category_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='sno',
            new_name='s_no',
        ),
    ]
